version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:iam::634553025965:role/ecsTaskExecutionRole"
        LoadBalancerInfo:
          ContainerName: "cdapp"
          ContainerPort: 80
